### ISSUE TITLE
Add Global context fields when creating ecs_logger::format

### ISSUE THREAD

**Issue by rdifrango** [ciffelia/ecs-logger#1]
As I logged over [here](https://github.com/elastic/ecs-logging-python/issues/57), I'd like the ability to add global fields that are attached to all records as this part of how to enable traceability and is supported by the other ECS implementations I've used.

I know in the Java, Python, and Node implementations these fields are emitted alongside the other fields and are covered by [this](https://www.elastic.co/guide/en/ecs/1.12/ecs-base.html#field-tags) of the spec.

**Note:** Rust newbie here so not sure if I could contribute or not but would be willing to try.

**Comment by alexsanderp** [comment]
News?
