### ISSUE TITLE
Nested `log.level` fields (and others)

### ISSUE THREAD

**Issue by Gau-thier** [ciffelia/ecs-logger#21]
First of all, thanks for this lib, making ecs-logging easy on rust 🙏 .

After a quick look on the official ecs documentation for other languages ([the one for Python for example](https://www.elastic.co/guide/en/ecs-logging/python/master/installation.html#logging)), it appears that the `log.level` field (for example) is supposed to be nested:
``` JSON
{
    "@timestamp": "2024-12-12T09:54:02.262382Z",
    "log.level": "DEBUG",
    "message": "Beautiful log message",
    "ecs.version": "1.12.1",
    "log.origin": {
        "file": {
            "line": 136,
            "name": "items.rs"
        },
        "rust": {
            "target": "target_file",
            "module_path": "module_path",
            "file_path": "src/file.rs"
        }
    }
}
```

Should then be something like:
```JSON
{
    "@timestamp": "2024-12-12T09:54:02.262382Z",
    "log": {
        "level": "DEBUG",
        "origin": {
            "file": {
                "line": 136,
                "name": "items.rs"
            },
            "rust": {
                "target": "target_file",
                "module_path": "module_path",
                "file_path": "src/file.rs"
            }
        },
        "message": "Beautiful log message",
        "ecs": {
            "version": "1.12.1"
        }
    }
}
```

Moreover, in JSON, `log.level` means we want to access to the field `level` stored in the `log` Object.

This is an open question, I am wondering if I am misunderstanding something, or it the fields should be nested?

Cheers!

**Comment by ciffelia** [comment]
Thanks for your feedback! I don't think we should nest the `log.level` field.

The introduction page in the official documentation says:

> **Decently human-readable JSON structure**
> 
> The first three fields are [@]timestamp, log.level and message. This lets you easily read the logs in a terminal without needing a tool that converts the logs to plain-text.

https://www.elastic.co/guide/en/ecs-logging/overview/master/intro.html#_why_ecs_logging

Actually there's an example with unnested `log.level` field in the documentation page you provided (in "Standard Library logging Module" section).

```json
{
    "@timestamp": "2020-03-20T18:11:37.895Z",
    "log.level": "debug",
    "message": "Example message!",
    "ecs": {
        "version": "1.6.0"
    },
    "http": {
      "request": {
        "method": "get"
      }
    },
    "log": {
        "logger": "app",
        "origin": {
            "file": {
                "line": 14,
                "name": "test.py"
            },
            "function": "func"
        },
        "original": "Example message!"
    }
}
```

https://www.elastic.co/guide/en/ecs-logging/python/master/installation.html#logging

**Comment by Gau-thier** [comment]
Hi @ciffelia , thanks a lot for your answer!

> Actually there's an example with unnested log.level field in the documentation page you provided (in "Standard Library logging Module" section).
>
> ```JSON
> {
>     "@timestamp": "2020-03-20T18:11:37.895Z",
>     "log.level": "debug",
>     "message": "Example message!",
>     "ecs": {
>         "version": "1.6.0"
>     },
>     "http": {
>       "request": {
>         "method": "get"
>       }
>     },
>     "log": {
>         "logger": "app",
>         "origin": {
>             "file": {
>                 "line": 14,
>                 "name": "test.py"
>             },
>             "function": "func"
>         },
>         "original": "Example message!"
>     }
> }
>```
>
> https://www.elastic.co/guide/en/ecs-logging/python/master/installation.html#logging

This example in the official doc is weird, because there is `log.level` which is unnested, then `log` with nested fields `logger`, `origin` and `original`...

It looks like even the standard isn't totally sure of what should be done.

Hence, because of the ambiguous official doc, I agreed with you: I don't think we should nest the `log.level` field.
